### ISSUE TITLE
Set default dates on page load

### ISSUE THREAD

**Issue by AtomicGrog** [ModdedMinecraftClub/Mmcc.Stats#7]
Can we please default the dates on the input dialog box to something like:

From: 1 Week Ago
To: Today

Seems trivial to do this yourself when on the page but it has two benefits:

1. Makes a quick run a single click operation.
2. Reduces likelihood of anyone going back months for the sake of it.

**Comment by TraceLD** [comment]
Will most likely be added in the next release.

**Comment by TraceLD** [comment]
Added in #9 .
